### PR TITLE
提交entity

### PR DESCRIPTION
**Pull request by gxwuyingjun**

### CODE REVIEW

**Comment by Afauvre** [comment]
Hi there! Noticed you haven't gone through the Oasis KYC process yet. This is a requirement to receive your Oasis Quest rewards on the genesis. Please submit it asap: https://oasis-network-individual.synaps.io/

**Comment by Afauvre** [comment]
@gxwuyingjun

**Comment by gxwuyingjun** [comment]
> @gxwuyingjun

**Comment by gxwuyingjun** [comment]
Hello! Missing residency address information. Can I recommit again?







在 2020-09-04 11:50:13，"Afauvre" <notifications@github.com> 写道：

@gxwuyingjun

**Pull request closed without merging**
