### PR TITLE
Add Ostrovmaria80 entity

### PR DESCRIPTION
**Pull request by Ostrovmaria80**

### CODE REVIEW

**Comment by Afauvre** [comment]
Hi there! Noticed you haven't gone through the Oasis KYC process yet. This is a requirement to receive your Oasis Quest rewards on the genesis. Please submit it asap: https://oasis-network-individual.synaps.io/

**Comment by Ostrovmaria80** [comment]
in fact, I have already passed KYC and I have it confirmed!  I don’t know what this message “Verification will start as soon as Oasis Network will approve you request” means, that my check was missing? or has my KYC been reset to zero?

**Comment by Afauvre** [comment]
what email did you use?

**Comment by Afauvre** [comment]
@Ostrovmaria80 hmm that means you have not gone through the process yet. We will email you offline to confirm what to do next.

**Pull request merged**
