### PR TITLE
Added entity package

### PR DESCRIPTION
**Pull request by dhruvmaloo**

### CODE REVIEW

**Comment by Afauvre** [comment]
@dhruvmaloo Can you go through the KYC process? This is a requirement before receiving your Quest rewards. https://oasis-network-individual.synaps.io/

**Comment by dhruvmaloo** [comment]
@Afauvre I tried doing KYC before and it was rejected. Since then, the upload option is not appearing for proof of residency. As soon as the option appears on the synaps platform, I'll upload the proof of residency.
Thanks

**Comment by Afauvre** [comment]
@dhruvmaloo were you able to resubmit?

**Comment by dhruvmaloo** [comment]
@Afauvre Yes, I have resubmitted and it has been successfully verified.

**Pull request merged**
